module.exports = {
    prefix: '¬',

    //Command Names
    base01: 'help',
    base02: 'who',
    base03: 'how',

    media01: 'audio',
    media02: 'images',
    media03: 'video',
    media04: 'mouse',

    text01: 'threestring',
    text02: 'penisstring',
    text03: 'goodstring',
    text04: 'poem',
    text05: 'wordsalad',
    text06: 'apples',
    text07: 'dwaialore',
    text08: 'neurolore',

    //Command descriptions, used in 'help'
    base01info: "Lists all available commands",
    base02info: "Bot introduction message",
    base03info: "Emotional status of the bot",
    media01info: "Posts a loud, unfunny noise",
    media02info: "Posts a funny image that will make you cum violently",
    media03info: "Posts a funny video which will induce psychopathy",
    media04info: "Obligatory mouse command",
    text01info: "Posts a random combination of words from three arrays",
    text02info: "Posts a random combination of words from two arrays but the first word is 'penis'",
    text03info: "Posts a fixed three word string at random out of the best (All of these can be produced by 'threestring', some predate the bot)",
    text04info: "Posts a random poem",
    text05info: "Posts a random word salad (Can be very NSFW)",
    text06info: "Displaces stock markets within the apple economy\n*Note: WE DON'T KNOW HOW THE PRICING OF APPLES WORK, STOP ASKING!*",
    text07info: "Displays lore relating to the Dwaia Project (Wow an actual serious command)",
    text08info: "Displays lore relating to the Neuroverse Project (Wow an actual serious command)",

    //Vocabulary arrays, used in 'threestring' and 'penisstring'
    vocabA: [
        'asshole',
        'autonomous',
        'belligerent',
        'cat',
        'chaotic',
        'comatose',
        'consumer-grade',
        'crystaline',
        'dick',
        'elegant',
        'elusive',
        'emaciated',
        'enigmatic',
        'euphoric',
        'fire',
        'free',
        'group',
        'hammer',
        'harmonious',
        'hyperactive',
        'industrial',
        'instrumental',
        'kilimanjaro',
        'liquid',
        'lucid',
        'melancholy',
        'mesozoic',
        'metamorphic',
        'nuclear',
        'obligatory',
        'penis',
        'pterodactyl',
        'quantum',
        'rapid',
        'spaghetti',
        'spiked',
        'stellated',
        'tactical',
        'testicle',
        'thunderous',
        'truncated',
        'underrated',
        'unicorn',
        'women',
        'yeti'
    ],
    vocabB: [
        'abuse',
        'anchor',
        'carpet',
        'child',
        'clamp',
        'crusher',
        'cum',
        'earthquake',
        'edm',
        'egg',
        'embryo',
        'eye',
        'faggot',
        'fart',
        'feedback',
        'flaying',
        'fuelled',
        'fusion',
        'hamster',
        'hentai',
        'histamine',
        'hitting',
        'hydrocarbon',
        'intrusion',
        'jackhammer',
        'karaoke',
        'lawnmower',
        'masturbation',
        'menstruation',
        'mind',
        'moshpit',
        'neo',
        'overwatch',
        'playground',
        'poo',
        'rape',
        'shrapnel',
        'slicing',
        'splitter',
        'ukulele',
        'underwear',
        'uterus',
        'wasp',
        'wifi'
    ],
    vocabC: [
        'abortion',
        'adventure',
        'airstrike',
        'algorithm',
        'alliance',
        'amputation',
        'anniversary',
        'array',
        'atrophy',
        'autobiography',
        'autopsy',
        'avalanche',
        'bananas',
        'biscuit',
        'bitch',
        'bloodbath',
        'bolognese',
        'bomber',
        'capsule',
        'cartel',
        'charge',
        'collapse',
        'collection',
        'complex',
        'concept',
        'consciousness',
        'contract',
        'cross-section',
        'escalation',
        'cycle',
        'declaration',
        'destruction',
        'detonation',
        'disorder',
        'dubstep',
        'duplicate',
        'elemental',
        'equity',
        'event',
        'exorcism',
        'extension',
        'extrapolation',
        'fetish',
        'fruit',
        'hallucination',
        'implement',
        'indigo',
        'inducement',
        'infestation',
        'inhibitor',
        'intake',
        'investigation',
        'isomorphism',
        'judgement',
        'loop',
        'mania',
        'manifold',
        'manipulator',
        'massacre',
        'matrix',
        'mesh',
        'message',
        'misery',
        'mutilator',
        'okkeyobiat',
        'overlay',
        'pact',
        'play',
        'plight',
        'policy',
        'prolapse',
        'protocol',
        'post-modernism',
        'psychopathy',
        'quotient',
        'rampage',
        'removal',
        'revolution',
        'robot',
        'smasher',
        'special',
        'speech',
        'supplement',
        'support',
        'surgery',
        'syndicate',
        'therapy',
        'time',
        'toy',
        'transfusion',
        'ultimate',
        'underground',
        'volcanism',
        'warfare',
        'washer'
    ]
}